config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'welcome/index'
  get 'welcome/serve_pdf', to: 'welcome#serve_pdf', as: 'serve_welcome_pdf'

  resources :guests do
    resources :plus_ones
    member do
      get :confirm
      patch :complete
    end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end 

app/models/admin_user.rb
# frozen_string_literal: true

#
# ActiveAdmin console user.
#
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
# frozen_string_literal: true

#
# A guest or plus one.
#
class Attendee < ApplicationRecord
  scope :diet?, -> { where.not(diet: nil) }
  scope :child?, -> { where(child: true) }
end

app/models/concerns/findable_with_token.rb
# frozen_string_literal: true

#
# Make a model findable only when a secure token is provided.
#
module FindableWithToken
  extend ActiveSupport::Concern

  ID_TOKEN_RX = /\A(\d+)-(\w+)\z/.freeze

  included do
    has_secure_token

    def to_param
      id ? "#{id}-#{token}" : nil
    end

    def self.find_by_id_token(id_token)
      raise ActiveRecord::RecordNotFound unless id_token =~ ID_TOKEN_RX

      id = Regexp.last_match(1)
      token = Regexp.last_match(2)

      record = find(id)
      raise ActiveRecord::RecordNotFound unless
        ActiveSupport::SecurityUtils.secure_compare(record.token, token)

      record
    end
  end
end

app/models/guest.rb
# frozen_string_literal: true

#
# A primary guest.
#
class Guest < ApplicationRecord
  include FindableWithToken

  auto_strip_attributes :email, :first_name, :last_name, :diet, :songs, :notes

  validates :email, presence: true, uniqueness: true
  validates :email, format: Devise.email_regexp, allow_blank: true

  validates :first_name, presence: true, if: :persisted?
  validates :first_name, length: { maximum: 1024 }
  validates :last_name, presence: true, if: :persisted?
  validates :last_name, length: { maximum: 1024 }

  def name
    "#{first_name} #{last_name}"
  end

  def name_with_email
    "#{name} <#{email}>"
  end

  # Don't allow long or odd names in emails; may be spam.
  def email_safe_salutation
    return 'Hola,' if
      first_name.blank? || first_name !~ /\A[\p{Word}\s'-]{1,30}\z/i

    "Querido/a #{first_name},"
  end

  validates :diet, length: { maximum: 8192 }
  validates :songs, length: { maximum: 8192 }
  validates :notes, length: { maximum: 8192 }

  
  has_many :plus_ones, dependent: :destroy

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :attending, -> { confirmed.where(attending: true) }
  scope :not_attending, -> { confirmed.where(attending: false) }
end

app/models/plus_one.rb
# frozen_string_literal: true

#
# An extra guest.
#
class PlusOne < ApplicationRecord
  belongs_to :guest

  auto_strip_attributes :first_name, :last_name, :diet

  validates :first_name, presence: true
  validates :first_name, length: { maximum: 1024 }
  validates :last_name, presence: true
  validates :last_name, length: { maximum: 1024 }

  def name
    "#{first_name} #{last_name}"
  end

  validates :diet, length: { maximum: 8192 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  if ENV['BASIC_AUTH_NAME'] && ENV['BASIC_AUTH_PASSWORD']
    http_basic_authenticate_with \
      name: ENV['BASIC_AUTH_NAME'],
      password: ENV['BASIC_AUTH_PASSWORD']
  end
end

app/controllers/guests_controller.rb
# frozen_string_literal: true

class GuestsController < ApplicationController
  def new
    respond_to :html

    @guest = Guest.new
  end

  def create
    respond_to :html

    @guest = Guest.new(guest_params)
    unless ENV['RECAPTCHA_SECRET_KEY'].blank? || verify_recaptcha(model: @guest)
      render :new
      return
    end

    if @guest.save
      redirect_to guest_path(@guest)
    else
      existing_guest = Guest.find_by(email: guest_params[:email])
      if existing_guest
        @guest = existing_guest
        GuestMailer.welcome_back_email(@guest).deliver_now
        render :new_exists
      else
        render :new
      end
    end
  end

  def show
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
  end

  def update
    @guest = Guest.find_by_id_token(params[:id])

    if @guest.update(guest_params)
      if @guest.attending?
        redirect_to guest_plus_ones_path(@guest)
      else
        redirect_to confirm_guest_path(@guest)
      end
    else
      render :show
    end
  end

  def confirm
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
  end

  def complete
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
    Guest.transaction do
      @guest.update!(guest_params)
      @guest.touch :confirmed_at
    end
    GuestMailer.confirmation_email(@guest).deliver_now
  end

  private

  def guest_params
    params.require(:guest).permit(
      :email, :first_name, :last_name, :attending, :diet, :songs, :notes
    )
  end
end

app/controllers/plus_ones_controller.rb
# frozen_string_literal: true

class PlusOnesController < ApplicationController
  before_action do
    @guest = Guest.find_by_id_token(params[:guest_id])
  end

  def new
    respond_to :html
    @plus_one = @guest.plus_ones.new
  end

  def create
    respond_to :html
    @plus_one = @guest.plus_ones.new(plus_one_params)
    if @plus_one.save
      redirect_to guest_plus_ones_path(@guest)
    else
      render :new
    end
  end

  def index
    respond_to :html
    @plus_ones = @guest.plus_ones.order(:first_name, :last_name)
  end

  def edit
    @plus_one = @guest.plus_ones.find(params[:id])
    respond_to :html
  end

  def update
    @plus_one = @guest.plus_ones.find(params[:id])

    if @plus_one.update(plus_one_params)
      redirect_to guest_plus_ones_path(@guest)
    else
      render :edit
    end
  end

  def destroy
    respond_to :html
    @plus_one = @guest.plus_ones.find_by(id: params[:id])
    @plus_one&.destroy
    redirect_to guest_plus_ones_path(@guest)
  end

  private

  def plus_one_params
    params.require(:plus_one).permit(:first_name, :last_name, :diet, :child)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @google_maps_url = 'https://goo.gl/maps/Cd9kNRrWZcqsdZok6'
    @party_url = 'https://goo.gl/maps/8XQ533kjxabYfh2x5'

    @cool_earth_url = serve_welcome_pdf_url
  end

  def serve_pdf
    pdf_filename = Rails.root.join('app/assets/pdfs/cuentas.pdf')
    send_file(pdf_filename, filename: "cuentas.pdf", type: "application/pdf")
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(key)
    case key
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end

  def time_until_wedding(wedding_date)
    wedding_time = DateTime.parse("2023-12-26 20:00:00")

    diff_in_seconds = (wedding_time - DateTime.now) * 24 * 60 * 60 # Convert difference to seconds

    full_days = (diff_in_seconds / (24 * 60 * 60)).to_i
    remaining_seconds_after_days = diff_in_seconds - (full_days * 24 * 60 * 60)
  
    hours = (remaining_seconds_after_days / (60 * 60)).to_i
    remaining_seconds_after_hours = remaining_seconds_after_days - (hours * 60 * 60)
  
    minutes = (remaining_seconds_after_hours / 60).to_i
    seconds = (remaining_seconds_after_hours - (minutes * 60)).to_i
  
    [full_days, hours, minutes, seconds]
    end


  def errors_for(object)
    return unless object.errors.any?

    content_tag(:div, class: 'mb-3 card border-danger') do
      concat(content_tag(:div, class: 'card-header bg-danger text-white') do
        concat "Oops, #{pluralize(object.errors.count, 'problem')}:"
      end)
      concat(content_tag(:ul, class: 'mb-0 list-group list-group-flush') do
        object.errors.full_messages.each do |msg|
          concat content_tag(:li, msg, class: 'list-group-item')
        end
      end)
    end
  end
end

app/helpers/guests_helper.rb
# frozen_string_literal: true

module GuestsHelper
end

app/helpers/plus_ones_helper.rb
# frozen_string_literal: true

module PlusOnesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/application/_mailing_address.html.erb
<strong>Alert</strong><br>
Qikiqtaaluk Region, Nunavut<br>
Canada<br>

app/views/application/_party_address.html.erb
<div class="text-center">

<strong>La Quinta de Bella Vista</strong><br>
Quirno 2700<br>
Bella Vista
</div>

app/views/application/_wedding_address.html.erb
<div class="text-center">
<strong>Parroquia San Francisco Solano</strong><br>
Sourdeaux 2199<br>
Bella Vista
</div>

app/views/guests/_dietary_preferences.html.erb
<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :diet, 'Menú especial', class: 'col-form-label' %>
  </div>
  <div class="col-md-9">
    <%= form.text_area :diet, id: "#{id_stem}_diet", class: 'form-control' %>
    <small class="form-text text-muted">Por ejemplo: vegano, vegetariano, celiaco, alergias o intolerancias.</small>
  </div>
</div>

app/views/guests/_leader.html.erb
<div id="guests-leader" class="jumbotron text-center">
  <div class="container">
    <h1>RSVP</h1>
  </div>
</div>

app/views/guests/_name.html.erb
<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :first_name, 'Nombre', class: 'col-form-label' %>
    <span class="wedding-required">*</span>
  </div>
  <div class="col-md-9">
    <%= form.text_field :first_name, id: "#{id_stem}_first_name", class: 'form-control', autofocus: true, required: true %>
  </div>
</div>

<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :last_name, 'Apellido', class: 'col-form-label' %>
    <span class="wedding-required">*</span>
  </div>
  <div class="col-md-9">
    <%= form.text_field :last_name, id: "#{id_stem}_last_name", class: 'form-control', required: true %>
  </div>
</div>

app/views/guests/_rsvp_nav.html.erb
<nav class="guests-rsvp-nav">
  <ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <%= link_to '1. Sobre Vos', guest_path(@guest), class: ['nav-link', active == 1 ? 'active' : ''] %>
    </li>
    <li class="nav-item">
      <% if active >= 2 %>
        <%= link_to '2. Acompañantes', guest_plus_ones_path(@guest), class: ['nav-link', active == 2 ? 'active' : ''] %>
      <% else %>
        <a class="nav-link <%= active == 2 ? 'active' : '' %>">2. Acompañantes</a>
      <% end %>
    </li>
    <li class="nav-item">
      <% if active >= 3 %>
        <%= link_to '3. Confirmar', confirm_guest_path(@guest), class: ['nav-link', active == 3 ? 'active' : ''] %>
      <% else %>
        <a class="nav-link <%= active == 3 ? 'active' : '' %>">3. Confirmar</a>
      <% end %>
    </li>
  </ul>
</nav>

app/views/guests/complete.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <h2>Gracias!</h2>
      <p>Te enviamos un mail a <tt><%= @guest.email %></tt>.</p>
      <p>Si no lo recibis en 5 minutos, revisa la carpeta de SPAM <%= mail_to ENV['CONTACT_EMAIL'], 'contactanos' %>.</p>
      <p>El mail contiene un link donde vas a poder actualizar tu RSVP si lo necesitaras.</p>
      <p><%= link_to 'Volver a la pagina principal', root_path %></p>
    </div>
  </div>
</div>

app/views/guests/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <%= render partial: 'rsvp_nav', locals: { active: 3 } %>

      <h2>Confirmar</h2>

      <%= form_with(model: @guest, url: complete_guest_path(@guest), local: true) do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <% if @guest.attending? %>
      <h3>Tus detalles</h3>
      <div class="card mb-3">
        <h5 class="card-header"><%= @guest.name %></h5>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              Email
            </div>
            <div class="col-md-8">
              <p><tt><%= @guest.email %></tt></p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              Menú Especial
            </div>
            <div class="col-md-8">
              <% if @guest.diet.present? %>
                <pre><%= @guest.diet %></pre>
              <% else %>
                <p>(No indica)</p>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              Canción que no puede faltar
            </div>
            <div class="col-md-8">
              <% if @guest.songs.present? %>
                <pre><%= @guest.songs %></pre>
              <% else %>
                <p>(No indica)</p>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-right">
              <%= link_to 'Edit', guest_path(@guest), class: 'card-link', data: { disable_with: 'Loading...' } %>
            </div>
          </div>
        </div>
      </div>

      <h3>Acompañante</h3>
      <% if @guest.plus_ones.any? %>
        <%= render @guest.plus_ones %>
      <% else %>
        <p>(No indica &mdash; just you.)</p>
      <% end %>
      <% else %>
      <p>Lamentamos que no puedas venir!</p>
      <h3>Detalles</h3>
      <div class="card mb-3">
        <h5 class="card-header"><%= @guest.name %></h5>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              Email
            </div>
            <div class="col-md-8">
              <p><tt><%= @guest.email %></tt></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

      <h3>Comentarios?</h3>

      <%= form.text_area :notes, class: 'form-control' %>
      <small class="form-text text-muted">Algo más que te gustaría hacernos saber?</small>

      <div class="row guests-buttons">
        <div class="offset-md-3 col-md-6 text-center">
          <%= form.submit 'Enviar', class: 'btn btn-primary', data: { disable_with: 'Enviando...' } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/guests/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <p>Por favor ingresa tu mail antes de empezar.</p>
      <%= form_with scope: :guest, url: guests_path, local: true do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :email, class: 'col-form-label' %>
        </div>
        <div class="col-md-9">
          <%= form.email_field :email, id: 'guest_email', class: 'form-control', autofocus: true, required: true %>
        </div>
      </div>

      <div class="row guests-buttons">
        <div class="offset-md-3 col-md-6 text-center">
          <%- if ENV['RECAPTCHA_SECRET_KEY'].blank? -%>
          <%= form.submit 'Continuar', class: 'btn btn-primary', data: { disable_with: 'Enviando...' } %>
          <%- else -%>
          <%= invisible_recaptcha_tags text: 'Continuar', class: 'btn btn-primary', data: { disable_with: 'Enviando...' } %>
          <%- end -%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/guests/new_exists.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <h2>HOLA, OTRA VEZ!</h2>
      <p>Parece que ya registraste tu RSVP. Asi que te enviamos un link para que puedas actualizarlo.</p>
      <p>Por favor checkea tu mail: <tt><%= @guest.email %></tt> incluso la carpeta SPAM!</p>
      <p>Si no recibis tu mail por favor <%= mail_to ENV['CONTACT_EMAIL'], 'contactanos' %>.</p>
    </div>
  </div>
</div>

app/views/guests/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <%= render partial: 'rsvp_nav', locals: { active: 1 } %>

      <h2>SOBRE VOS</h2>

      <%= form_with(model: @guest, method: :patch, local: true, id: 'guest-edit-form') do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :email, class: 'col-form-label' %>
          <span class="wedding-required">*</span>
        </div>
        <div class="col-md-9">
          <%= form.email_field :email, id: 'guest_email', class: 'form-control', required: true %>
        </div>
      </div>

      <%= render partial: 'name', locals: { form: form, id_stem: 'guest' } %>

      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <p><strong>Venís?</strong></p>
          <div class="form-check form-check-inline">
            <%= form.radio_button :attending, 'true', checked: true, id: 'guest_attending_true', class: 'form-check-input' %>
            <%= form.label :attending, 'Si', value: 'true', class: 'form-check-label' %>
          </div>
          <div class="form-check form-check-inline">
            <%= form.radio_button :attending, 'false', id: 'guest_attending_false', class: 'form-check-input' %>
            <%= form.label :attending, 'No', value: 'false', class: 'form-check-label' %>
          </div>
        </div>
      </div>

      <div class="guest-attending-only">
      <%= render partial: 'dietary_preferences', locals: { form: form, id_stem: 'guest' } %>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :songs, 'Cancion que no puede faltar', class: 'col-form-label' %>
        </div>
        <div class="col-md-9">
          <%= form.text_area :songs, id: 'guest_songs', class: 'form-control' %>
          <small class="form-text text-muted">Estamos armando nuestra playlist! Pongamos la tuya!</small>
        </div>
      </div>
      </div>

      <div class="row guests-buttons">
        <div class="col-md-3">
          <span class="wedding-required">* Obligatorio</span>
        </div>
        <div class="col-md-6 text-center">
          <%= form.submit 'Continuar', class: 'btn btn-primary', data: { disable_with: 'Enviando...' } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :wedding_name %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, class: flash_class(key)) do -%>
        <%= value %>
      <% end -%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/plus_ones/_form.html.erb
<%= form_with(model: [@guest, @plus_one], local: true) do |form| %>
  <div class="row">
    <div class="col-md-12">
      <%= errors_for(@plus_one) %>
    </div>
  </div>

  <%= render partial: 'guests/name', locals: { form: form, id_stem: 'plus_one' } %>

  <%= render partial: 'guests/dietary_preferences', locals: { form: form, id_stem: 'plus_one' } %>

  <div class="form-group row">
  <div class="offset-md-3 col-md-9">
    <div class="form-check form-check-inline">
      <%= form.check_box :child, id: 'plus_one_child', class: 'form-check-input' %>
      <%= form.label :child, 'Menú infantil', class: 'form-check-label' %>
    </div>
  </div>
</div>


  <div class="row guests-buttons">
    <div class="col-md-3">
      <span class="wedding-required">* Obligatorio</span>
    </div>
    <div class="col-md-6 text-center">
      <%= form.submit submit_action, class: 'btn btn-primary', data: { disable_with: 'Enviando...' } %>
    </div>
    <div class="col-md-3 text-right">
      <%= link_to 'Cancel', guest_plus_ones_path(@guest), class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/plus_ones/_plus_one.html.erb
<div class="card mb-3">
  <h5 class="card-header"><%= plus_one.name %></h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        Menú especial
      </div>
      <div class="col-md-8">
        <% if plus_one.diet.present? %>
          <pre><%= plus_one.diet %></pre>
        <% else %>
          <p>(No indica)</p>
        <% end %>
      </div>
    </div>
    <div class="row">
    <div class="col-md-4">
    Menú infantil
  </div>
  <div class="col-md-8">
  <p><%= plus_one.child ? 'Si' : 'No' %></p>
</div>

    </div>
    <div class="row">
      <div class="col-md-12 text-right">
        <%= link_to 'Editar', edit_guest_plus_one_path(plus_one.guest, plus_one), class: 'card-link', data: { disable_with: 'Loading...' } %>
        <%= link_to 'Quitar', guest_plus_one_path(plus_one.guest, plus_one), method: :delete, class: 'card-link', data: { disable_with: 'Quitando...', confirm: 'Estas seguro?' } %>
      </div>
    </div>
  </div>
</div>

app/views/plus_ones/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Edit Plus One</h2>
      <%= render partial: 'form', locals: { submit_action: 'Agregar' } %>
    </div>
  </div>
</div>

app/views/plus_ones/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Acompañante</h2>
      <p>Por favor indicanos si traes algun acompañante.
      <p>&nbsp;</p>

      <% if @plus_ones.any? %>
        <%= render @plus_ones %>
      <% else %>
        <p>No se agregó acompañante.</p>
      <% end %>
      <% if @plus_ones.count == 0 || ["gonzalez", "azar", "romero", "brombini", "romero victorica", "victorica", "lopez", "lopez arias", "barrera", "figueroa", "fernandez", "bordenave"].include?(I18n.transliterate(@guest.last_name).downcase) %>
      <p>
    <%= link_to 'Agregar acompañante', new_guest_plus_one_path(@guest), class: 'btn btn-primary', data: { disable_with: 'Loading...' } %>
</p>
<% end %>

      <p>&nbsp;</p>
      <p class="guests-buttons">
        <%= link_to 'Continuar', confirm_guest_path(@guest), class: 'btn btn-primary' %>
      </p>
    </div>
  </div>
</div>

app/views/plus_ones/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Agregar acompañante</h2>
      <%= render partial: 'form', locals: { submit_action: 'Agregar acompañante' } %>
    </div>
  </div>
</div>

app/views/welcome/_calendar_svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 8 8">
  <path d="M0 0v2h7v-2h-7zm0 3v4.91c0 .05.04.09.09.09h6.81c.05 0 .09-.04.09-.09v-4.91h-7zm1 1h1v1h-1v-1zm2 0h1v1h-1v-1zm2 0h1v1h-1v-1zm-4 2h1v1h-1v-1zm2 0h1v1h-1v-1z" />
</svg>

app/views/welcome/_footer.html.erb
<footer id="welcome-index-footer" class="page-footer">
  <div class="container-fluid">
    <div class="row">
      <div id="welcome-index-footer-cta" class="col-md-12 text-center">
        <%= link_to 'Confirmá tu asistencia!', new_guest_path, class: 'btn btn-primary wedding-cta-btn' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center" id="welcome-index-footer-credits">
        <small><% t :photo_credits %></small>
      </div>
    </div>
  </div>
</footer>

app/views/welcome/_jumbo.html.erb
<section id="welcome-index-leader" class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= t :wedding_couple_names %></h1>
    <p class="leader-date">
      <%= t :wedding_date %>, <%= t :wedding_location %>
      <p id="countdown" data-wedding-time="<%= DateTime.parse(t(:wedding_date) + ' 09:30:00').to_i %>">
      Faltan <span id="days">-</span> dias <span id="hours">-</span> horas <span id="minutes">-</span> minutos, y <span id="seconds">-</span> segundos!
  </p>
      
    </p>


  </div>
</section>

app/views/welcome/_map_marker_svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 8 8">
  <path d="M3 0c-1.66 0-3 1.34-3 3 0 2 3 5 3 5s3-3 3-5c0-1.66-1.34-3-3-3zm0 1c1.11 0 2 .9 2 2 0 1.11-.89 2-2 2-1.1 0-2-.89-2-2 0-1.1.9-2 2-2z" transform="translate(1)" />
</svg>

app/views/welcome/_plan.html.erb
<section id="welcome-index-wedding-plan-leader" class="jumbotron text-center">
  <div class="container">
    <h1>EXTRAS</h1>
  </div>
</section>
<section id="welcome-index-wedding-plan">
  <div class="container">
    <div class="row">
      <div class="offset-md-3 col-md-6">
        <h2>QUERES REGALARNOS?</h2>
        <p>El mejor regalo es que vengas, pero si tenés ganas de regalarnos algo te dejamos acá la info!.        
        <p class="text-center"><%= link_to 'Descargar PDF', @cool_earth_url, class: 'btn btn-primary wedding-cta-btn' %></p>
        <h2>RSVP (Por favor, confirma tu asistencia)</h2>
        <p>Por favor, confirmanos tu asistencia lo antes posible para saber quién viene y asegurarnos de reservar tu lugar. Si resulta que no podés venir, por favor, avisanos tan pronto como puedas.        
        </p>
      </div>
    </div>
  </div>
</section>